export const  ADD_TO_CART="ADD_TO_CART"
export const  DELETE_FROM_CART="DELETE_FROM_CART"
export const  ADD_QTY="ADD_QTY"
export const  DELETE_QTY="DELETE_QTY"

export const SET_INGREDIENTS="SET_INGREDIENTS"